(define (problem 50_crates_5_persons)
(:domain lab1.2)
(:objects
	h - helicopter
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	food - content
	medicin - content
	p1 - person
	p2 - person
	p3 - person
	p4 - person
	p5 - person
)
(:init
	(at h depot)
	(helicopter-empty h)
	(at p1 loc19)
	(at p2 loc49)
	(at p3 loc50)
	(at p4 loc19)
	(at p5 loc49)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(at crate25 depot)
	(at crate26 depot)
	(at crate27 depot)
	(at crate28 depot)
	(at crate29 depot)
	(at crate30 depot)
	(at crate31 depot)
	(at crate32 depot)
	(at crate33 depot)
	(at crate34 depot)
	(at crate35 depot)
	(at crate36 depot)
	(at crate37 depot)
	(at crate38 depot)
	(at crate39 depot)
	(at crate40 depot)
	(at crate41 depot)
	(at crate42 depot)
	(at crate43 depot)
	(at crate44 depot)
	(at crate45 depot)
	(at crate46 depot)
	(at crate47 depot)
	(at crate48 depot)
	(at crate49 depot)
	(at crate50 depot)
	(crate-content crate1 medicin)
	(crate-content crate2 medicin)
	(crate-content crate3 medicin)
	(crate-content crate4 medicin)
	(crate-content crate5 medicin)
	(crate-content crate6 medicin)
	(crate-content crate7 medicin)
	(crate-content crate8 medicin)
	(crate-content crate9 medicin)
	(crate-content crate10 food)
	(crate-content crate11 food)
	(crate-content crate12 food)
	(crate-content crate13 food)
	(crate-content crate14 food)
	(crate-content crate15 food)
	(crate-content crate16 food)
	(crate-content crate17 food)
	(crate-content crate18 food)
	(crate-content crate19 food)
	(crate-content crate20 food)
	(crate-content crate21 food)
	(crate-content crate22 food)
	(crate-content crate23 food)
	(crate-content crate24 food)
	(crate-content crate25 food)
	(crate-content crate26 food)
	(crate-content crate27 food)
	(crate-content crate28 food)
	(crate-content crate29 food)
	(crate-content crate30 food)
	(crate-content crate31 food)
	(crate-content crate32 food)
	(crate-content crate33 food)
	(crate-content crate34 food)
	(crate-content crate35 food)
	(crate-content crate36 food)
	(crate-content crate37 food)
	(crate-content crate38 food)
	(crate-content crate39 food)
	(crate-content crate40 food)
	(crate-content crate41 food)
	(crate-content crate42 food)
	(crate-content crate43 food)
	(crate-content crate44 food)
	(crate-content crate45 food)
	(crate-content crate46 food)
	(crate-content crate47 food)
	(crate-content crate48 food)
	(crate-content crate49 food)
	(crate-content crate50 food)
)
(:goal (and (at h depot)
	(person-got-help p1 medicin)
    (person-got-help p2 medicin)
    (person-got-help p3 food)
    (person-got-help p4 medicin)
    (person-got-help p5 medicin)
	))
)
